// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImYRsfJ-yVQzwSdsJt94EadFC69S7Ca0',
    appId: '1:1018809096666:web:4136adc7daa2126bb648e3',
    messagingSenderId: '1018809096666',
    projectId: 'kcsmobileapp-7a5c8',
    authDomain: 'kcsmobileapp-7a5c8.firebaseapp.com',
    storageBucket: 'kcsmobileapp-7a5c8.firebasestorage.app',
    measurementId: 'G-NDEK7D53GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5PS1wmNK8F3q2reSsTiDBQzyJMjavCY',
    appId: '1:1018809096666:android:44163348a8d162e1b648e3',
    messagingSenderId: '1018809096666',
    projectId: 'kcsmobileapp-7a5c8',
    storageBucket: 'kcsmobileapp-7a5c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2od5nQLp82VQcXfNhBveR9rIKYCwFZbQ',
    appId: '1:1018809096666:ios:c9ba86f96fd75d74b648e3',
    messagingSenderId: '1018809096666',
    projectId: 'kcsmobileapp-7a5c8',
    storageBucket: 'kcsmobileapp-7a5c8.firebasestorage.app',
    iosBundleId: 'com.example.kcsmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2od5nQLp82VQcXfNhBveR9rIKYCwFZbQ',
    appId: '1:1018809096666:ios:c9ba86f96fd75d74b648e3',
    messagingSenderId: '1018809096666',
    projectId: 'kcsmobileapp-7a5c8',
    storageBucket: 'kcsmobileapp-7a5c8.firebasestorage.app',
    iosBundleId: 'com.example.kcsmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImYRsfJ-yVQzwSdsJt94EadFC69S7Ca0',
    appId: '1:1018809096666:web:98d33939a1b8ea2ab648e3',
    messagingSenderId: '1018809096666',
    projectId: 'kcsmobileapp-7a5c8',
    authDomain: 'kcsmobileapp-7a5c8.firebaseapp.com',
    storageBucket: 'kcsmobileapp-7a5c8.firebasestorage.app',
    measurementId: 'G-P4VNKR5HFH',
  );
}
